# Site settings
title: Australian Timetable Association
email: webmaster@timetable.org.au
description: > # this means to ignore newlines until "baseurl:"
  The ATA (Australian Timetable Association) is an organisation for anyone
  interested in the study of transport timetables, schedules, maps and
  associated literature.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.timetable.org.au" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
named_cdn_url: "http://cdn.timetable.org.au" # URL of CDN in use with same suffix
secure_cdn_url: "https://efb778d9cbba3f4c5d31-2a2416132ea09b6c13760470ead1b56d.ssl.cf1.rackcdn.com" # URL of CDN that is secure, not necessarily same suffix

plugins:
  - jekyll-pandoc

# Build settings
markdown: Pandoc

exclude:
- README.md
- fixups_sh
- cdnb.robots.txt
