# Site settings
title: Australian Timetable Association
email: webmaster@austta.org.au
description: > # this means to ignore newlines until "baseurl:"
  The ATA (Australian Timetable Association) is an organisation for anyone
  interested in the study of transport timetables, schedules, maps and
  associated literature.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://timetable.org.au" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

plugins:
  - jekyll-pandoc

# Build settings
markdown: Pandoc

exclude:
- README.md
- fixups_sh
- cdnb.robots.txt
